# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  
  config.vm.define :haproxy do |haproxy|
    haproxy.vm.box = "bento/ubuntu-22.04"
    haproxy.vm.network :private_network, ip: "192.168.100.2"
    haproxy.vm.hostname = "haproxy"
  end
  
  config.vm.define :worker1 do |worker1|
    worker1.vm.box = "bento/ubuntu-22.04"
    worker1.vm.network :private_network, ip: "192.168.100.3"
    worker1.vm.hostname = "worker1"
  end

  config.vm.define :worker2 do |worker2|
    worker2.vm.box = "bento/ubuntu-22.04"
    worker2.vm.network :private_network, ip: "192.168.100.4"
    worker2.vm.hostname = "worker2"
  end
end